server:
  port: 10086


#文档转换路径配置
doc:
  convert:
    docpath: /Users/suyu/Desktop/doc-convert/tmp/doc/
    imgspath: /Users/suyu/Desktop/doc-convert/tmp/imgs/
aliyun:
  oss:
    accessKeyId:
    accessKeySecret:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket: suyublog


